[package]
name = "orchestrator"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "*"
argh = "*"
clap = "*"
console = "*"
dialoguer = "*"
exitcode = "*"
glob = "*"
indicatif = "*"
lazy_static = "*"
regex = "*"
typed-builder = "*"
