[package]
name = "croptest"
version = "0.1.0"
edition = "2021"

[dependencies]

argh = "*"
itertools = "*"
plotz-color = { path = "../../plotz-color" }
plotz-core = { path = "../../plotz-core" }
plotz-geometry = { path = "../../plotz-geometry" }
tracing = "*"
tracing-subscriber = "*"
