[package]
name = "plotz-geojson"
version = "0.1.0"
edition = "2021"

[dependencies]
plotz-geometry = { path = "../plotz-geometry" }
serde_json = "*"
anyhow = "*"
tracing = "*"
itertools = "*"


[dev-dependencies]
assert_matches = "*"
itertools = "*"