[package]
name = "tilings"
version = "0.1.0"
edition = "2021"

[dependencies]

argh = "*"
float-cmp = "*"
lazy_static = "*"
plotz-color = { path = "../../plotz-color" }
plotz-core = { path = "../../plotz-core" }
plotz-geometry = { path = "../../plotz-geometry" }
