[package]
name = "plotz-core"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "*"
plotz-color = { path = "../plotz-color" }
plotz-geojson = { path = "../plotz-geojson" }
plotz-geometry = { path = "../plotz-geometry" }
serde_json = "*"
string-interner = "*"
thiserror = "*"
cairo-rs = { version = "0.14.9", features = ["png", "svg"] }

[dev-dependencies]
tempdir = "*"