[package]
name = "plotz-shp"
version = "0.1.0"
edition = "2021"

[dependencies]
shapefile = "0.3.0"
plotz-geometry = { path = "../plotz-geometry" }
serde_json = "*"
string-interner = "*"
thiserror = "*"
lazy_static = "*"

[dev-dependencies]